#chain network
net: "livenet"


#rds
rds:
  dsn: "user:password@tcp(localhost:3306)/metaid_media_db?charset=utf8mb4&parseTime=True&loc=Local&timeout=5s&readTimeout=30s"
  max_open_conns: 1000
  max_idle_conns: 50

# Indexer configuration
indexer:
  port: "7281"   # Indexer service port
  scan_interval: 10
  batch_size: 100
  start_height: 0
  swagger_base_url: "localhost:7281"  # Swagger API base URL (shown in Swagger UI)

# Uploader configuration
uploader:
  port: "7282"  # Uploader service port
  max_file_size: 10485760
  fee_rate: 1
  swagger_base_url: "localhost:7282"  # Swagger API base URL (shown in Swagger UI)

# Blockchain configuration
chain:
  rpc_url: "http://127.0.0.1:9882"
  rpc_user: "rpcuser"
  rpc_pass: "rpcpassword"
  start_height: 0

# Storage configuration
storage:
  type: "local"  # local/oss
  local:
    base_path: "./data/files"
  oss:
    endpoint: ""
    access_key: ""
    secret_key: ""
    bucket: ""


