// Package indexer Code generated by swaggo/swag. DO NOT EDIT
package indexer

import "github.com/swaggo/swag"

const docTemplateindexer = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/avatars": {
            "get": {
                "description": "Query avatar list with cursor pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer Avatar Query"
                ],
                "summary": "Query avatar list",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Cursor (last avatar ID)",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-media-service_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-media-service_controller_respond.IndexerAvatarListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/meta-media-service_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/avatars/address/{address}": {
            "get": {
                "description": "Query the latest avatar information by address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer Avatar Query"
                ],
                "summary": "Get latest avatar by address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-media-service_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-media-service_controller_respond.IndexerAvatarResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/meta-media-service_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/avatars/content/{pinId}": {
            "get": {
                "description": "Get avatar content by PIN ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "Indexer Avatar Query"
                ],
                "summary": "Get avatar content",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PIN ID",
                        "name": "pinId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/meta-media-service_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/avatars/metaid/{metaId}": {
            "get": {
                "description": "Query the latest avatar information by MetaID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer Avatar Query"
                ],
                "summary": "Get latest avatar by MetaID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "MetaID",
                        "name": "metaId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-media-service_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-media-service_controller_respond.IndexerAvatarResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/meta-media-service_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/files": {
            "get": {
                "description": "Query file list with cursor pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer File Query"
                ],
                "summary": "Query file list",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Cursor (last file ID)",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-media-service_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-media-service_controller_respond.IndexerFileListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/meta-media-service_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/files/content/{pinId}": {
            "get": {
                "description": "Get file content by PIN ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "Indexer File Query"
                ],
                "summary": "Get file content",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PIN ID",
                        "name": "pinId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/meta-media-service_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/files/creator/{address}": {
            "get": {
                "description": "Query file list by creator address with cursor pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer File Query"
                ],
                "summary": "Get files by creator address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Creator address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Cursor (last file ID)",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-media-service_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-media-service_controller_respond.IndexerFileListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/meta-media-service_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/files/metaid/{metaId}": {
            "get": {
                "description": "Query file list by creator MetaID with cursor pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer File Query"
                ],
                "summary": "Get files by creator MetaID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Creator MetaID",
                        "name": "metaId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Cursor (last file ID)",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-media-service_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-media-service_controller_respond.IndexerFileListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/meta-media-service_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/files/{pinId}": {
            "get": {
                "description": "Query file details by PIN ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer File Query"
                ],
                "summary": "Get file by PIN ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "PIN ID",
                        "name": "pinId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-media-service_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-media-service_controller_respond.IndexerFileResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/meta-media-service_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/stats": {
            "get": {
                "description": "Get indexer statistics (total files count, etc.)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer Status"
                ],
                "summary": "Get statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-media-service_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-media-service_controller_respond.IndexerStatsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/meta-media-service_controller_respond.Response"
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "Get indexer synchronization status (includes latest block height from node)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Indexer Status"
                ],
                "summary": "Get sync status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/meta-media-service_controller_respond.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/meta-media-service_controller_respond.IndexerSyncStatusResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/meta-media-service_controller_respond.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "meta-media-service_controller_respond.IndexerAvatarListResponse": {
            "type": "object",
            "properties": {
                "avatars": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/meta-media-service_controller_respond.IndexerAvatarResponse"
                    }
                },
                "has_more": {
                    "type": "boolean",
                    "example": true
                },
                "next_cursor": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "meta-media-service_controller_respond.IndexerAvatarResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa"
                },
                "avatar": {
                    "type": "string",
                    "example": "indexer/avatar/mvc/xyz789/xyz789i0.jpg"
                },
                "block_height": {
                    "type": "integer",
                    "example": 12345
                },
                "chain_name": {
                    "type": "string",
                    "example": "mvc"
                },
                "content_type": {
                    "type": "string",
                    "example": "image/jpeg"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "file_extension": {
                    "type": "string",
                    "example": ".jpg"
                },
                "file_hash": {
                    "type": "string",
                    "example": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
                },
                "file_md5": {
                    "type": "string",
                    "example": "d41d8cd98f00b204e9800998ecf8427e"
                },
                "file_size": {
                    "type": "integer",
                    "example": 102400
                },
                "file_type": {
                    "type": "string",
                    "example": "image"
                },
                "meta_id": {
                    "type": "string",
                    "example": "abc123def456..."
                },
                "pin_id": {
                    "description": "ID            int64     ` + "`" + `json:\"id\" example:\"1\"` + "`" + `",
                    "type": "string",
                    "example": "xyz789i0"
                },
                "timestamp": {
                    "type": "integer",
                    "example": 1699999999
                },
                "tx_id": {
                    "type": "string",
                    "example": "xyz789"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                }
            }
        },
        "meta-media-service_controller_respond.IndexerFileListResponse": {
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/meta-media-service_controller_respond.IndexerFileResponse"
                    }
                },
                "has_more": {
                    "type": "boolean",
                    "example": true
                },
                "next_cursor": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "meta-media-service_controller_respond.IndexerFileResponse": {
            "type": "object",
            "properties": {
                "block_height": {
                    "type": "integer",
                    "example": 12345
                },
                "chain_name": {
                    "type": "string",
                    "example": "mvc"
                },
                "content_type": {
                    "type": "string",
                    "example": "image/jpeg"
                },
                "creator_address": {
                    "type": "string",
                    "example": "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa"
                },
                "creator_meta_id": {
                    "type": "string",
                    "example": "abc123def456..."
                },
                "file_extension": {
                    "type": "string",
                    "example": ".jpg"
                },
                "file_hash": {
                    "type": "string",
                    "example": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
                },
                "file_md5": {
                    "type": "string",
                    "example": "d41d8cd98f00b204e9800998ecf8427e"
                },
                "file_name": {
                    "type": "string",
                    "example": "test.jpg"
                },
                "file_size": {
                    "type": "integer",
                    "example": 102400
                },
                "file_type": {
                    "type": "string",
                    "example": "image"
                },
                "operation": {
                    "type": "string",
                    "example": "create"
                },
                "owner_address": {
                    "type": "string",
                    "example": "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa"
                },
                "owner_meta_id": {
                    "type": "string",
                    "example": "abc123def456..."
                },
                "path": {
                    "type": "string",
                    "example": "/file/test.jpg"
                },
                "pin_id": {
                    "description": "ID             int64     ` + "`" + `json:\"id\" example:\"1\"` + "`" + `",
                    "type": "string",
                    "example": "abc123def456i0"
                },
                "storage_path": {
                    "description": "StorageType    string    ` + "`" + `json:\"storage_type\" example:\"oss\"` + "`" + `",
                    "type": "string",
                    "example": "indexer/mvc/pinid123i0.jpg"
                },
                "timestamp": {
                    "type": "integer",
                    "example": 1699999999
                },
                "tx_id": {
                    "type": "string",
                    "example": "abc123def456789"
                }
            }
        },
        "meta-media-service_controller_respond.IndexerStatsResponse": {
            "type": "object",
            "properties": {
                "total_files": {
                    "type": "integer",
                    "example": 12345
                }
            }
        },
        "meta-media-service_controller_respond.IndexerSyncStatusResponse": {
            "type": "object",
            "properties": {
                "chain_name": {
                    "description": "ID                int64     ` + "`" + `json:\"id\" example:\"1\"` + "`" + `",
                    "type": "string",
                    "example": "mvc"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "current_sync_height": {
                    "type": "integer",
                    "example": 12345
                },
                "latest_block_height": {
                    "type": "integer",
                    "example": 12350
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                }
            }
        },
        "meta-media-service_controller_respond.Response": {
            "description": "Unified API response structure",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {},
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "processingTime": {
                    "type": "integer",
                    "example": 123
                }
            }
        }
    }
}`

// SwaggerInfoindexer holds exported Swagger Info so clients can modify it
var SwaggerInfoindexer = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:7281",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Meta Media Indexer API",
	Description:      "Meta Media Indexer Service API, provides file query and download functionality",
	InfoInstanceName: "indexer",
	SwaggerTemplate:  docTemplateindexer,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoindexer.InstanceName(), SwaggerInfoindexer)
}
